INSERT INTO KAMERA (ID, ANZAHL_PIXEL, HERSTELLER, KAMERAMODELL, SENSORFORMAT) VALUES
    (NEXT VALUE FOR HIBERNATE_SEQUENCE, '22', 'Canon', '5D MARK III', 'KB' ),
    (NEXT VALUE FOR HIBERNATE_SEQUENCE, '24', 'Sony', 'Alpha 6600', 'APSC');
