INSERT INTO KAMERA (KAMERA_ID, ANZAHL_PIXEL, HERSTELLER, KAMERAMODELL, SENSORFORMAT) VALUES
    (NEXT VALUE FOR HIBERNATE_SEQUENCE, '22', 'CANON', '5D MARK III', 'KB' ),
    (NEXT VALUE FOR HIBERNATE_SEQUENCE, '24', 'SONY', 'Alpha 6600', 'APSC');
